### ISSUE TITLE
Somente eu fingindo que estou contribuindo pro seu repositório para fazer o curso da alura

### ISSUE THREAD

**Issue by joevtap** [CaiqueBrandani/Capacitacao-git-github#5]
Olha só, você recusou o meu PR #2 exatamente como eu pedi e agora eu consigo citar ele aqui, olha que legal

**Comment by JoaoLucasLD** [comment]
Olá, eu também estou fingindo contribuir para o projeto dele para fazer o curso da Alura. O meu PR é o #9. Belos cachorros.

**Comment by joevtap** [comment]
Nossa, que legal!

Sabemos usar o Github!!!
